//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorisShisaWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebUsers", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class WebUsers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLevelField, value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionDetails", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class SubscriptionDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetails", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class BookingDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberOfPeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingID {
            get {
                return this.BookingIDField;
            }
            set {
                if ((this.BookingIDField.Equals(value) != true)) {
                    this.BookingIDField = value;
                    this.RaisePropertyChanged("BookingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dates {
            get {
                return this.DatesField;
            }
            set {
                if ((this.DatesField.Equals(value) != true)) {
                    this.DatesField = value;
                    this.RaisePropertyChanged("Dates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberOfPeople {
            get {
                return this.NumberOfPeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberOfPeopleField, value) != true)) {
                    this.NumberOfPeopleField = value;
                    this.RaisePropertyChanged("NumberOfPeople");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Times {
            get {
                return this.TimesField;
            }
            set {
                if ((this.TimesField.Equals(value) != true)) {
                    this.TimesField = value;
                    this.RaisePropertyChanged("Times");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPriceField, value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsDetails", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class ProductsDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskDetails", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class TaskDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingID {
            get {
                return this.BookingIDField;
            }
            set {
                if ((this.BookingIDField.Equals(value) != true)) {
                    this.BookingIDField = value;
                    this.RaisePropertyChanged("BookingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusName {
            get {
                return this.CusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CusNameField, value) != true)) {
                    this.CusNameField = value;
                    this.RaisePropertyChanged("CusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dates {
            get {
                return this.DatesField;
            }
            set {
                if ((this.DatesField.Equals(value) != true)) {
                    this.DatesField = value;
                    this.RaisePropertyChanged("Dates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableNo {
            get {
                return this.TableNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNoField, value) != true)) {
                    this.TableNoField = value;
                    this.RaisePropertyChanged("TableNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Times {
            get {
                return this.TimesField;
            }
            set {
                if ((this.TimesField.Equals(value) != true)) {
                    this.TimesField = value;
                    this.RaisePropertyChanged("Times");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageVisit", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class PageVisit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfVisitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfVisits {
            get {
                return this.NumberOfVisitsField;
            }
            set {
                if ((this.NumberOfVisitsField.Equals(value) != true)) {
                    this.NumberOfVisitsField = value;
                    this.RaisePropertyChanged("NumberOfVisits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageName {
            get {
                return this.PageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PageNameField, value) != true)) {
                    this.PageNameField = value;
                    this.RaisePropertyChanged("PageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityLogs", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class ActivityLogs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActivitydateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activity {
            get {
                return this.ActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityField, value) != true)) {
                    this.ActivityField = value;
                    this.RaisePropertyChanged("Activity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Activitydate {
            get {
                return this.ActivitydateField;
            }
            set {
                if ((this.ActivitydateField.Equals(value) != true)) {
                    this.ActivitydateField = value;
                    this.RaisePropertyChanged("Activitydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportDetails", Namespace="http://schemas.datacontract.org/2004/07/DorisShisa")]
    [System.SerializableAttribute()]
    public partial class ReportDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUserDetails", ReplyAction="http://tempuri.org/IService1/InsertUserDetailsResponse")]
        string InsertUserDetails(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUserDetails", ReplyAction="http://tempuri.org/IService1/InsertUserDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertUserDetailsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/logUsers", ReplyAction="http://tempuri.org/IService1/logUsersResponse")]
        string logUsers(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/logUsers", ReplyAction="http://tempuri.org/IService1/logUsersResponse")]
        System.Threading.Tasks.Task<string> logUsersAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSubscriptions", ReplyAction="http://tempuri.org/IService1/InsertSubscriptionsResponse")]
        string InsertSubscriptions(DorisShisaWebApplication.ServiceReference1.SubscriptionDetails Subscribers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSubscriptions", ReplyAction="http://tempuri.org/IService1/InsertSubscriptionsResponse")]
        System.Threading.Tasks.Task<string> InsertSubscriptionsAsync(DorisShisaWebApplication.ServiceReference1.SubscriptionDetails Subscribers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ForgotPassword", ReplyAction="http://tempuri.org/IService1/ForgotPasswordResponse")]
        string ForgotPassword(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ForgotPassword", ReplyAction="http://tempuri.org/IService1/ForgotPasswordResponse")]
        System.Threading.Tasks.Task<string> ForgotPasswordAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        string ChangePassword(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select", ReplyAction="http://tempuri.org/IService1/SelectResponse")]
        DorisShisaWebApplication.ServiceReference1.WebUsers Select(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select", ReplyAction="http://tempuri.org/IService1/SelectResponse")]
        System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.WebUsers> SelectAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserRegDetails", ReplyAction="http://tempuri.org/IService1/UpdateUserRegDetailsResponse")]
        string UpdateUserRegDetails(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserRegDetails", ReplyAction="http://tempuri.org/IService1/UpdateUserRegDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateUserRegDetailsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserRegDetails", ReplyAction="http://tempuri.org/IService1/GetUserRegDetailsResponse")]
        System.Data.DataSet GetUserRegDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserRegDetails", ReplyAction="http://tempuri.org/IService1/GetUserRegDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserRegDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserRegDetails", ReplyAction="http://tempuri.org/IService1/DeleteUserRegDetailsResponse")]
        bool DeleteUserRegDetails(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserRegDetails", ReplyAction="http://tempuri.org/IService1/DeleteUserRegDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserRegDetailsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/bookuser", ReplyAction="http://tempuri.org/IService1/bookuserResponse")]
        string bookuser(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/bookuser", ReplyAction="http://tempuri.org/IService1/bookuserResponse")]
        System.Threading.Tasks.Task<string> bookuserAsync(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOrderDetails", ReplyAction="http://tempuri.org/IService1/InsertOrderDetailsResponse")]
        string InsertOrderDetails(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOrderDetails", ReplyAction="http://tempuri.org/IService1/InsertOrderDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertOrderDetailsAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCusEmail", ReplyAction="http://tempuri.org/IService1/GetCusEmailResponse")]
        DorisShisaWebApplication.ServiceReference1.WebUsers GetCusEmail(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCusEmail", ReplyAction="http://tempuri.org/IService1/GetCusEmailResponse")]
        System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.WebUsers> GetCusEmailAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetuserOrderDetails", ReplyAction="http://tempuri.org/IService1/GetuserOrderDetailsResponse")]
        DorisShisaWebApplication.ServiceReference1.OrderDetails GetuserOrderDetails(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetuserOrderDetails", ReplyAction="http://tempuri.org/IService1/GetuserOrderDetailsResponse")]
        System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.OrderDetails> GetuserOrderDetailsAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        bool DeleteOrder(DorisShisaWebApplication.ServiceReference1.OrderDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Vieworder", ReplyAction="http://tempuri.org/IService1/VieworderResponse")]
        System.Data.DataSet Vieworder(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Vieworder", ReplyAction="http://tempuri.org/IService1/VieworderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> VieworderAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProducts", ReplyAction="http://tempuri.org/IService1/AddProductsResponse")]
        string AddProducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails Products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProducts", ReplyAction="http://tempuri.org/IService1/AddProductsResponse")]
        System.Threading.Tasks.Task<string> AddProductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails Products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Data.DataSet GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRoducts", ReplyAction="http://tempuri.org/IService1/DeleteRoductsResponse")]
        bool DeleteRoducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRoducts", ReplyAction="http://tempuri.org/IService1/DeleteRoductsResponse")]
        System.Threading.Tasks.Task<bool> DeleteRoductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedProducts", ReplyAction="http://tempuri.org/IService1/FetchUpdatedProductsResponse")]
        System.Data.DataSet FetchUpdatedProducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedProducts", ReplyAction="http://tempuri.org/IService1/FetchUpdatedProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedProductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProducts", ReplyAction="http://tempuri.org/IService1/UpdateProductsResponse")]
        string UpdateProducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProducts", ReplyAction="http://tempuri.org/IService1/UpdateProductsResponse")]
        System.Threading.Tasks.Task<string> UpdateProductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertbookingtask", ReplyAction="http://tempuri.org/IService1/InsertbookingtaskResponse")]
        string Insertbookingtask(DorisShisaWebApplication.ServiceReference1.TaskDetails Task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertbookingtask", ReplyAction="http://tempuri.org/IService1/InsertbookingtaskResponse")]
        System.Threading.Tasks.Task<string> InsertbookingtaskAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails Task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOrdertask", ReplyAction="http://tempuri.org/IService1/InsertOrdertaskResponse")]
        string InsertOrdertask(DorisShisaWebApplication.ServiceReference1.TaskDetails Task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOrdertask", ReplyAction="http://tempuri.org/IService1/InsertOrdertaskResponse")]
        System.Threading.Tasks.Task<string> InsertOrdertaskAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails Task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAssigned", ReplyAction="http://tempuri.org/IService1/InsertAssignedResponse")]
        string InsertAssigned(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAssigned", ReplyAction="http://tempuri.org/IService1/InsertAssignedResponse")]
        System.Threading.Tasks.Task<string> InsertAssignedAsync(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTaskAssigned", ReplyAction="http://tempuri.org/IService1/InsertTaskAssignedResponse")]
        string InsertTaskAssigned(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTaskAssigned", ReplyAction="http://tempuri.org/IService1/InsertTaskAssignedResponse")]
        System.Threading.Tasks.Task<string> InsertTaskAssignedAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingDetails", ReplyAction="http://tempuri.org/IService1/GetBookingDetailsResponse")]
        System.Data.DataSet GetBookingDetails(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingDetails", ReplyAction="http://tempuri.org/IService1/GetBookingDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookingDetailsAsync(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderDetails", ReplyAction="http://tempuri.org/IService1/GetOrderDetailsResponse")]
        System.Data.DataSet GetOrderDetails(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderDetails", ReplyAction="http://tempuri.org/IService1/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOrderDetailsAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingTAskDetails", ReplyAction="http://tempuri.org/IService1/GetBookingTAskDetailsResponse")]
        System.Data.DataSet GetBookingTAskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingTAskDetails", ReplyAction="http://tempuri.org/IService1/GetBookingTAskDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookingTAskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderTaskDetails", ReplyAction="http://tempuri.org/IService1/GetOrderTaskDetailsResponse")]
        System.Data.DataSet GetOrderTaskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderTaskDetails", ReplyAction="http://tempuri.org/IService1/GetOrderTaskDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOrderTaskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBookingTAskDetails", ReplyAction="http://tempuri.org/IService1/DeleteBookingTAskDetailsResponse")]
        bool DeleteBookingTAskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBookingTAskDetails", ReplyAction="http://tempuri.org/IService1/DeleteBookingTAskDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookingTAskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrderTaskDetails", ReplyAction="http://tempuri.org/IService1/DeleteOrderTaskDetailsResponse")]
        bool DeleteOrderTaskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrderTaskDetails", ReplyAction="http://tempuri.org/IService1/DeleteOrderTaskDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderTaskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBookingTAskDetails", ReplyAction="http://tempuri.org/IService1/UpdateBookingTAskDetailsResponse")]
        string UpdateBookingTAskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBookingTAskDetails", ReplyAction="http://tempuri.org/IService1/UpdateBookingTAskDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateBookingTAskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrderTaskDetails", ReplyAction="http://tempuri.org/IService1/UpdateOrderTaskDetailsResponse")]
        string UpdateOrderTaskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrderTaskDetails", ReplyAction="http://tempuri.org/IService1/UpdateOrderTaskDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateOrderTaskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductName", ReplyAction="http://tempuri.org/IService1/GetProductNameResponse")]
        DorisShisaWebApplication.ServiceReference1.OrderDetails[] GetProductName(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductName", ReplyAction="http://tempuri.org/IService1/GetProductNameResponse")]
        System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.OrderDetails[]> GetProductNameAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserOrderProductDetails", ReplyAction="http://tempuri.org/IService1/GetUserOrderProductDetailsResponse")]
        DorisShisaWebApplication.ServiceReference1.OrderDetails GetUserOrderProductDetails(string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserOrderProductDetails", ReplyAction="http://tempuri.org/IService1/GetUserOrderProductDetailsResponse")]
        System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.OrderDetails> GetUserOrderProductDetailsAsync(string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPageVisit", ReplyAction="http://tempuri.org/IService1/InsertPageVisitResponse")]
        string InsertPageVisit(DorisShisaWebApplication.ServiceReference1.PageVisit PageVisitTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPageVisit", ReplyAction="http://tempuri.org/IService1/InsertPageVisitResponse")]
        System.Threading.Tasks.Task<string> InsertPageVisitAsync(DorisShisaWebApplication.ServiceReference1.PageVisit PageVisitTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertActivityLogs", ReplyAction="http://tempuri.org/IService1/InsertActivityLogsResponse")]
        string InsertActivityLogs(DorisShisaWebApplication.ServiceReference1.ActivityLogs ActivityTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertActivityLogs", ReplyAction="http://tempuri.org/IService1/InsertActivityLogsResponse")]
        System.Threading.Tasks.Task<string> InsertActivityLogsAsync(DorisShisaWebApplication.ServiceReference1.ActivityLogs ActivityTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubscriptionsReport", ReplyAction="http://tempuri.org/IService1/SubscriptionsReportResponse")]
        string SubscriptionsReport(DorisShisaWebApplication.ServiceReference1.ReportDetails Report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubscriptionsReport", ReplyAction="http://tempuri.org/IService1/SubscriptionsReportResponse")]
        System.Threading.Tasks.Task<string> SubscriptionsReportAsync(DorisShisaWebApplication.ServiceReference1.ReportDetails Report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookingReport", ReplyAction="http://tempuri.org/IService1/BookingReportResponse")]
        string BookingReport(DorisShisaWebApplication.ServiceReference1.ReportDetails Report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookingReport", ReplyAction="http://tempuri.org/IService1/BookingReportResponse")]
        System.Threading.Tasks.Task<string> BookingReportAsync(DorisShisaWebApplication.ServiceReference1.ReportDetails Report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderReport", ReplyAction="http://tempuri.org/IService1/OrderReportResponse")]
        string OrderReport(DorisShisaWebApplication.ServiceReference1.ReportDetails Report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderReport", ReplyAction="http://tempuri.org/IService1/OrderReportResponse")]
        System.Threading.Tasks.Task<string> OrderReportAsync(DorisShisaWebApplication.ServiceReference1.ReportDetails Report);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DorisShisaWebApplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DorisShisaWebApplication.ServiceReference1.IService1>, DorisShisaWebApplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertUserDetails(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.InsertUserDetails(WebUsers);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserDetailsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.InsertUserDetailsAsync(WebUsers);
        }
        
        public string logUsers(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.logUsers(WebUsers);
        }
        
        public System.Threading.Tasks.Task<string> logUsersAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.logUsersAsync(WebUsers);
        }
        
        public string InsertSubscriptions(DorisShisaWebApplication.ServiceReference1.SubscriptionDetails Subscribers) {
            return base.Channel.InsertSubscriptions(Subscribers);
        }
        
        public System.Threading.Tasks.Task<string> InsertSubscriptionsAsync(DorisShisaWebApplication.ServiceReference1.SubscriptionDetails Subscribers) {
            return base.Channel.InsertSubscriptionsAsync(Subscribers);
        }
        
        public string ForgotPassword(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.ForgotPassword(WebUsers);
        }
        
        public System.Threading.Tasks.Task<string> ForgotPasswordAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.ForgotPasswordAsync(WebUsers);
        }
        
        public string ChangePassword(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.ChangePassword(WebUsers);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.ChangePasswordAsync(WebUsers);
        }
        
        public DorisShisaWebApplication.ServiceReference1.WebUsers Select(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.Select(WebUsers);
        }
        
        public System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.WebUsers> SelectAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.SelectAsync(WebUsers);
        }
        
        public string UpdateUserRegDetails(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.UpdateUserRegDetails(WebUsers);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserRegDetailsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.UpdateUserRegDetailsAsync(WebUsers);
        }
        
        public System.Data.DataSet GetUserRegDetails() {
            return base.Channel.GetUserRegDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserRegDetailsAsync() {
            return base.Channel.GetUserRegDetailsAsync();
        }
        
        public System.Data.DataSet FetchUpdatedRecords(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.FetchUpdatedRecords(WebUsers);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.FetchUpdatedRecordsAsync(WebUsers);
        }
        
        public bool DeleteUserRegDetails(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.DeleteUserRegDetails(WebUsers);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserRegDetailsAsync(DorisShisaWebApplication.ServiceReference1.WebUsers WebUsers) {
            return base.Channel.DeleteUserRegDetailsAsync(WebUsers);
        }
        
        public string bookuser(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings) {
            return base.Channel.bookuser(Bookings);
        }
        
        public System.Threading.Tasks.Task<string> bookuserAsync(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings) {
            return base.Channel.bookuserAsync(Bookings);
        }
        
        public string InsertOrderDetails(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.InsertOrderDetails(OrderTable);
        }
        
        public System.Threading.Tasks.Task<string> InsertOrderDetailsAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.InsertOrderDetailsAsync(OrderTable);
        }
        
        public DorisShisaWebApplication.ServiceReference1.WebUsers GetCusEmail(string Email) {
            return base.Channel.GetCusEmail(Email);
        }
        
        public System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.WebUsers> GetCusEmailAsync(string Email) {
            return base.Channel.GetCusEmailAsync(Email);
        }
        
        public DorisShisaWebApplication.ServiceReference1.OrderDetails GetuserOrderDetails(string Email) {
            return base.Channel.GetuserOrderDetails(Email);
        }
        
        public System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.OrderDetails> GetuserOrderDetailsAsync(string Email) {
            return base.Channel.GetuserOrderDetailsAsync(Email);
        }
        
        public bool DeleteOrder(DorisShisaWebApplication.ServiceReference1.OrderDetails products) {
            return base.Channel.DeleteOrder(products);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails products) {
            return base.Channel.DeleteOrderAsync(products);
        }
        
        public System.Data.DataSet Vieworder(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.Vieworder(OrderTable);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VieworderAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.VieworderAsync(OrderTable);
        }
        
        public string AddProducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails Products) {
            return base.Channel.AddProducts(Products);
        }
        
        public System.Threading.Tasks.Task<string> AddProductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails Products) {
            return base.Channel.AddProductsAsync(Products);
        }
        
        public System.Data.DataSet GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public bool DeleteRoducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails products) {
            return base.Channel.DeleteRoducts(products);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRoductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails products) {
            return base.Channel.DeleteRoductsAsync(products);
        }
        
        public System.Data.DataSet FetchUpdatedProducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails products) {
            return base.Channel.FetchUpdatedProducts(products);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedProductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails products) {
            return base.Channel.FetchUpdatedProductsAsync(products);
        }
        
        public string UpdateProducts(DorisShisaWebApplication.ServiceReference1.ProductsDetails products) {
            return base.Channel.UpdateProducts(products);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductsAsync(DorisShisaWebApplication.ServiceReference1.ProductsDetails products) {
            return base.Channel.UpdateProductsAsync(products);
        }
        
        public string Insertbookingtask(DorisShisaWebApplication.ServiceReference1.TaskDetails Task) {
            return base.Channel.Insertbookingtask(Task);
        }
        
        public System.Threading.Tasks.Task<string> InsertbookingtaskAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails Task) {
            return base.Channel.InsertbookingtaskAsync(Task);
        }
        
        public string InsertOrdertask(DorisShisaWebApplication.ServiceReference1.TaskDetails Task) {
            return base.Channel.InsertOrdertask(Task);
        }
        
        public System.Threading.Tasks.Task<string> InsertOrdertaskAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails Task) {
            return base.Channel.InsertOrdertaskAsync(Task);
        }
        
        public string InsertAssigned(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings) {
            return base.Channel.InsertAssigned(Bookings);
        }
        
        public System.Threading.Tasks.Task<string> InsertAssignedAsync(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings) {
            return base.Channel.InsertAssignedAsync(Bookings);
        }
        
        public string InsertTaskAssigned(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.InsertTaskAssigned(OrderTable);
        }
        
        public System.Threading.Tasks.Task<string> InsertTaskAssignedAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.InsertTaskAssignedAsync(OrderTable);
        }
        
        public System.Data.DataSet GetBookingDetails(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings) {
            return base.Channel.GetBookingDetails(Bookings);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookingDetailsAsync(DorisShisaWebApplication.ServiceReference1.BookingDetails Bookings) {
            return base.Channel.GetBookingDetailsAsync(Bookings);
        }
        
        public System.Data.DataSet GetOrderDetails(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.GetOrderDetails(OrderTable);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOrderDetailsAsync(DorisShisaWebApplication.ServiceReference1.OrderDetails OrderTable) {
            return base.Channel.GetOrderDetailsAsync(OrderTable);
        }
        
        public System.Data.DataSet GetBookingTAskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask) {
            return base.Channel.GetBookingTAskDetails(BookingTask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookingTAskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask) {
            return base.Channel.GetBookingTAskDetailsAsync(BookingTask);
        }
        
        public System.Data.DataSet GetOrderTaskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask) {
            return base.Channel.GetOrderTaskDetails(OrderTask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOrderTaskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask) {
            return base.Channel.GetOrderTaskDetailsAsync(OrderTask);
        }
        
        public bool DeleteBookingTAskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask) {
            return base.Channel.DeleteBookingTAskDetails(BookingTask);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookingTAskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask) {
            return base.Channel.DeleteBookingTAskDetailsAsync(BookingTask);
        }
        
        public bool DeleteOrderTaskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask) {
            return base.Channel.DeleteOrderTaskDetails(OrderTask);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderTaskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask) {
            return base.Channel.DeleteOrderTaskDetailsAsync(OrderTask);
        }
        
        public string UpdateBookingTAskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask) {
            return base.Channel.UpdateBookingTAskDetails(BookingTask);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBookingTAskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails BookingTask) {
            return base.Channel.UpdateBookingTAskDetailsAsync(BookingTask);
        }
        
        public string UpdateOrderTaskDetails(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask) {
            return base.Channel.UpdateOrderTaskDetails(OrderTask);
        }
        
        public System.Threading.Tasks.Task<string> UpdateOrderTaskDetailsAsync(DorisShisaWebApplication.ServiceReference1.TaskDetails OrderTask) {
            return base.Channel.UpdateOrderTaskDetailsAsync(OrderTask);
        }
        
        public DorisShisaWebApplication.ServiceReference1.OrderDetails[] GetProductName(string Email) {
            return base.Channel.GetProductName(Email);
        }
        
        public System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.OrderDetails[]> GetProductNameAsync(string Email) {
            return base.Channel.GetProductNameAsync(Email);
        }
        
        public DorisShisaWebApplication.ServiceReference1.OrderDetails GetUserOrderProductDetails(string ProductName) {
            return base.Channel.GetUserOrderProductDetails(ProductName);
        }
        
        public System.Threading.Tasks.Task<DorisShisaWebApplication.ServiceReference1.OrderDetails> GetUserOrderProductDetailsAsync(string ProductName) {
            return base.Channel.GetUserOrderProductDetailsAsync(ProductName);
        }
        
        public string InsertPageVisit(DorisShisaWebApplication.ServiceReference1.PageVisit PageVisitTable) {
            return base.Channel.InsertPageVisit(PageVisitTable);
        }
        
        public System.Threading.Tasks.Task<string> InsertPageVisitAsync(DorisShisaWebApplication.ServiceReference1.PageVisit PageVisitTable) {
            return base.Channel.InsertPageVisitAsync(PageVisitTable);
        }
        
        public string InsertActivityLogs(DorisShisaWebApplication.ServiceReference1.ActivityLogs ActivityTable) {
            return base.Channel.InsertActivityLogs(ActivityTable);
        }
        
        public System.Threading.Tasks.Task<string> InsertActivityLogsAsync(DorisShisaWebApplication.ServiceReference1.ActivityLogs ActivityTable) {
            return base.Channel.InsertActivityLogsAsync(ActivityTable);
        }
        
        public string SubscriptionsReport(DorisShisaWebApplication.ServiceReference1.ReportDetails Report) {
            return base.Channel.SubscriptionsReport(Report);
        }
        
        public System.Threading.Tasks.Task<string> SubscriptionsReportAsync(DorisShisaWebApplication.ServiceReference1.ReportDetails Report) {
            return base.Channel.SubscriptionsReportAsync(Report);
        }
        
        public string BookingReport(DorisShisaWebApplication.ServiceReference1.ReportDetails Report) {
            return base.Channel.BookingReport(Report);
        }
        
        public System.Threading.Tasks.Task<string> BookingReportAsync(DorisShisaWebApplication.ServiceReference1.ReportDetails Report) {
            return base.Channel.BookingReportAsync(Report);
        }
        
        public string OrderReport(DorisShisaWebApplication.ServiceReference1.ReportDetails Report) {
            return base.Channel.OrderReport(Report);
        }
        
        public System.Threading.Tasks.Task<string> OrderReportAsync(DorisShisaWebApplication.ServiceReference1.ReportDetails Report) {
            return base.Channel.OrderReportAsync(Report);
        }
    }
}
